name: Build Release

on:
  push:
    branches:
      - master
  
  watch:
    types: [started]

jobs:
  buildRelease:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build Release
      run: |
        ls -alh
        make
        strip darkhttpd
        ls -alh

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      with:
        name: release
        path: darkhttpd